name: SAST - Semgrep Security Scan

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  schedule:
    - cron: "0 2 * * *" # Daily at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep:
    name: Semgrep Security Analysis
    runs-on: ubuntu-latest

    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')

    container:
      # A Docker image with Semgrep installed
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep with comprehensive rulesets
        run: |
          echo "Starting Semgrep scan..."
          echo "Working directory: $(pwd)"
          echo "Files to scan:"
          find . -name "*.js" -o -name "*.ts" -o -name "*.tsx" | head -10

          # Run Semgrep and capture exit code
          semgrep ci \
            --config=p/security-audit \
            --config=p/nodejs \
            --config=p/typescript \
            --config=p/react \
            --config=p/owasp-top-ten \
            --config=p/secrets \
            --sarif \
            --output=semgrep.sarif \
            --timeout=300 \
            --verbose || true
            
          echo "Semgrep scan completed"
          echo "SARIF file status:"
          ls -la *.sarif || echo "No SARIF files found"

          # Create empty SARIF if none exists
          if [ ! -f "semgrep.sarif" ]; then
            echo "Creating empty SARIF file for upload"
            cat > semgrep.sarif << 'EOF'
          {
            "version": "2.1.0",
            "schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "runs": []
          }
          EOF
          fi
        env:
          # Use GitHub token for improved rate limiting
          SEMGREP_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep
        if: always()

      - name: Upload Semgrep results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-security-results
          path: semgrep.sarif
          retention-days: 30
        if: always()
